### PR TITLE
Removed duplicate apt-get update.

### PR DESCRIPTION
**Pull request by BeingTomGreen**

### CODE REVIEW

**Comment by alxy** [comment]
+1 for this one.
3 times apt-get update is definetly not neccessary.

**Comment by alxy** [comment]
@JeffreyWay : There is still one update too much: https://github.com/JeffreyWay/Vagrant-Setup/blob/master/install.sh#L18-L19

**Comment by JeffreyWay** [comment]
I think that second one is needed.

**Comment by alxy** [comment]
You are right. Missed that you added a package-source there. You could restructure it, but it is a minor thing :P

**Pull request merged**
